# Generated by Django 3.1.5 on 2021-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField(default='channel')),
                ('mem1_name', models.TextField(default='member1', max_length=20)),
                ('mem2_name', models.TextField(default='member2', max_length=20)),
                ('mem3_name', models.TextField(default='member3', max_length=20)),
                ('mem4_name', models.TextField(default='member4', max_length=20)),
                ('mem5_name', models.TextField(default='member5', max_length=20)),
                ('password', models.TextField(max_length=15)),
                ('adminMsg', models.TextField()),
                ('msgTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('name', models.TextField(default='name', max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('has_chat', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='name', max_length=20)),
                ('password', models.TextField(max_length=15)),
                ('myMsg', models.TextField()),
                ('contactMsg', models.TextField()),
                ('msgTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(default='Group')),
                ('mem1_name', models.TextField(default='member1', max_length=20)),
                ('mem2_name', models.TextField(default='member2', max_length=20)),
                ('mem3_name', models.TextField(default='member3', max_length=20)),
                ('mem4_name', models.TextField(default='member4', max_length=20)),
                ('mem5_name', models.TextField(default='member5', max_length=20)),
                ('password', models.TextField(max_length=15)),
                ('myMsg', models.TextField()),
                ('mem1Msg', models.TextField()),
                ('mem2Msg', models.TextField()),
                ('mem3Msg', models.TextField()),
                ('mem4Msg', models.TextField()),
                ('mem5Msg', models.TextField()),
                ('msgTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonality',
            fields=[
                ('first_name', models.TextField(default='first name', max_length=20)),
                ('last_name', models.TextField(default='last name', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(default='chatroom', max_length=20)),
                ('password', models.TextField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
