# Generated by Django 3.1.5 on 2021-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0002_auto_20210121_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='public',
            name='myMsg',
        ),
        migrations.RemoveField(
            model_name='public',
            name='password',
        ),
        migrations.RemoveField(
            model_name='publicinfo',
            name='password',
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='mem1_name',
            field=models.TextField(default='member1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='mem2_name',
            field=models.TextField(default='member2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='mem3_name',
            field=models.TextField(default='member3', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='mem4_name',
            field=models.TextField(default='member4', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='mem5_name',
            field=models.TextField(default='member5', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='mem1_name',
            field=models.TextField(default='member1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='mem2_name',
            field=models.TextField(default='member2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='mem3_name',
            field=models.TextField(default='member3', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='mem4_name',
            field=models.TextField(default='member4', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='mem5_name',
            field=models.TextField(default='member5', max_length=20, null=True),
        ),
    ]
