# Generated by Django 3.1.5 on 2021-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0003_auto_20210122_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='adminMsg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='msgTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='mem1Msg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='mem2Msg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='mem3Msg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='mem4Msg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='mem5Msg',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='msgTime',
            field=models.DateTimeField(null=True),
        ),
    ]
