# Generated by Django 3.1.5 on 2021-01-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0005_auto_20210127_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_admin',
        ),
    ]
