# Generated by Django 3.1.5 on 2021-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0006_remove_channel_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='channel_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicinfo',
            name='group_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
